-- =============================================================================
-- I.S.O PRO — RPC: referencias de materiais (Postgres + snapshot JSON)
-- =============================================================================
-- Implementacao canonica: supabase/migrations/20260604130000_iso_pro_security_hardening.sql
--
-- Parametros:
--   p_tenant_id     uuid
--   p_material_ids  bigint[]
--
-- Cliente:
--   await supabase.rpc('iso_pro_materiais_uso_nos_modulos', {
--     p_tenant_id: tenantId,
--     p_material_ids: [1, 2, 3],
--   });
-- =============================================================================

-- Aplicar a migracao no projeto Supabase antes de usar no cliente desktop 0.1.25+.
