import { describe, expect, it } from 'vitest';
import { analisarRelatorioFinalObra } from './relatorioFinalObraAnalise';
import { montarContextoJsonParaIa } from './relatorioFinalObraContextoIa';

describe('montarContextoJsonParaIa', () => {
  it('não inclui data URLs de fotos no payload', () => {
    const dados = {
      contexto: {
        numeroRelatorio: '',
        registrado: false,
        geradoEm: '2026-05-16T12:00:00.000Z',
        cliente: 'C',
        projeto: 'P',
        contrato: '',
        local: '',
        rodapeNome: '',
        rodapeCnpj: '',
      },
      totais: {
        documentos: 0,
        documentosCancelados: 0,
        recebimentos: 0,
        recebimentosCancelados: 0,
        rir: 0,
        rirCancelados: 0,
        rnc: 1,
        rncCancelados: 0,
        atendimentos: 0,
        atendimentosEstornados: 0,
        inventarios: 0,
        inventariosAbertos: 0,
        relatoriosFotograficos: 0,
        materiais: 0,
        colaboradores: 0,
        fornecedores: 0,
      },
      documentos: [],
      recebimentos: [],
      rir: [],
      rnc: [
        {
          id: '1',
          codigo: 'RNC-1',
          dataRegistro: '2026-01-01',
          setor: '',
          responsavel: '',
          descricao: 'x',
          status: 'aberto' as const,
          planoAcao: '',
          observacoes: '',
          recebimentoId: 'r',
          pedidoCompra: '',
          materialCodigo: '',
          materialDescricao: '',
          quantidadeRejeitada: 0,
          quantidadeRecebidaRef: 0,
          localArmazenagem: '',
          localArmazenagemOutro: '',
          tiposOcorrencia: {
            avariaFisica: true,
            quantidadeIncorreta: false,
            materialIncorreto: false,
            documentacaoFaltante: false,
            validadeExpirada: false,
            outro: false,
            outroTexto: '',
          },
          descricaoDetalhada: 'dano',
          evidencias: { fotosAnexadas: true, copiaPedido: false, copiaNf: false, laudoConferencia: false },
          evidenciasObservacao: '',
          acaoImediataTipo: '',
          acaoImediataObservacoes: '',
          analiseCausaRaiz: '',
          planoAcaoLinhas: [],
          encerramentoParecer: '',
          assinaturaResponsavelRnc: { nome: '', data: '' },
          assinaturaQualidade: { nome: '', data: '' },
          assinaturaFornecedor: { nome: '', data: '' },
          itensRnc: [
            {
              recebimentoItemId: 'i',
              incluir: true,
              codigoMaterial: '',
              descricaoMaterial: '',
              unidade: '',
              disciplina: '',
              localizacao: '',
              quantidadeRecebida: 1,
              quantidadeConferida: 0,
              pesoUnitario: 0,
              pesoTotal: 0,
              certificado: '',
              quantidadeRejeitada: 1,
              tiposOcorrencia: {
                avariaFisica: true,
                quantidadeIncorreta: false,
                materialIncorreto: false,
                documentacaoFaltante: false,
                validadeExpirada: false,
                outro: false,
                outroTexto: '',
              },
              descricaoDetalhada: '',
              fotosDataUrls: ['data:image/jpeg;base64,AAAA'],
              fotosDeclaradasSemArquivo: false,
            },
          ],
        },
      ],
      atendimentos: [],
      inventarios: [],
      relatoriosFotograficos: [],
    };
    const analise = analisarRelatorioFinalObra(dados as import('../types/relatorioFinalObra.types').RelatorioFinalObraDados);
    const json = JSON.stringify(montarContextoJsonParaIa(dados as import('../types/relatorioFinalObra.types').RelatorioFinalObraDados, analise));
    expect(json).not.toContain('data:image');
    expect(json).toContain('totalFotosItens');
  });
});
